### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by akandadai** [kalaspuff/tomodachi#1447]
The issue is because of this:
https://github.com/kalaspuff/tomodachi/blob/8a99a2a33a8188454820de0bf8f45ef65cea6b1e/tomodachi/envelope/json_base.py#L40-L43
and this:
https://github.com/kalaspuff/tomodachi/blob/8a99a2a33a8188454820de0bf8f45ef65cea6b1e/tomodachi/envelope/json_base.py#L58

looks like there are some cases where the message `data_encoding` is neither raw nor bas64_gzip_json which causes `data` to not be defined. The easy fix was to define data outside the scope or in an else case but this might not be the best way to fix this.

**Comment by kalaspuff** [comment]
Hi. Thanks for the report. I've added a PR to instead return a `None` value in case the data encoding for the processed message is unknown. https://github.com/kalaspuff/tomodachi/pull/1450

Usually this wouldn't happen unless a service that has been defined to use the `JsonBase` example envelope is receiving JSON data enveloped using another method on a topic which the service is subscribing. This may additionally point to that something else is set up incorrectly or that actually another custom enveloping class should be used within the service to accomodate those needs. 

In any way, it's better to let the function pass and let the users building the services define if they need the enveloped `data` value or if they want the entire message `payload` as can be specified in their function signatures. 🙇
