### ISSUE TITLE
[Request] SQS Subscriber with no Topic requirement

### ISSUE THREAD

**Issue by cboothe** [kalaspuff/tomodachi#1488]
I was looking to use this for a SQS queue subscriber, but don't want to make topic a requirement.

@tomodachi.aws_sns_sqs("example-topic", queue_name="example-queue")

versus

@tomodachi.aws_sqs(queue_name="example-queue")

Also how do you handle boto3.client('sqs').delete_message() ?
Looks like you are conditionally removing items from the queue.

cls.delete_message(receipt_handle, queue_url, context)

**Comment by cboothe** [comment]
@kalaspuff Would you be able to comment on this request? Thanks!

**Comment by cboothe** [comment]
Thanks @kalaspuff

**Comment by kalaspuff** [comment]
Included in the [0.21.5](https://github.com/kalaspuff/tomodachi/releases/tag/0.21.5) release. 🙏 🎉
