### ISSUE TITLE
Docker example fails during build. Unable to execute gcc

### ISSUE THREAD

**Issue by agonzalezl** [kalaspuff/tomodachi#1539]
Hello!

I was checking the repository and, in particular, the examples and I saw that the docker example fails when I try to build it.

The only problem is that the docker image is unable to find `gcc`. 

I am using a Mac with M1, but I am sure this is a generic problem.

I can add the installation of the `build-essential` package in the docker example.

The logs:

> => ERROR [2/3] RUN pip install tomodachi                                                                                                                                                              5.4s                                                                                                                                                                                              
 > [2/3] RUN pip install tomodachi:                                                                                                                                                                         
#5 0.875 Collecting tomodachi                                                                                                                                                                               
#5 0.905   Downloading tomodachi-0.21.7-py3-none-any.whl (91 kB)                                                                                                                                            
#5 0.960 Collecting aiobotocore<1.4.0,>=0.10.4                                                                                                                                                              
#5 0.969   Downloading aiobotocore-1.3.3.tar.gz (50 kB)                                                                                                                                                     
#5 1.465 Collecting botocore>=1.12.252
#5 1.480   Downloading botocore-1.23.7-py3-none-any.whl (8.1 MB)
#5 1.864 Collecting cchardet>=2.1.6
#5 1.874   Downloading cchardet-2.1.7.tar.gz (653 kB)
#5 2.107 Collecting aioamqp<0.15.0,>=0.13.0
#5 2.116   Downloading aioamqp-0.14.0-py35.py36.py37.py38-none-any.whl (19 kB)
#5 2.190 Collecting pytz
#5 2.198   Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
#5 2.234 Collecting colorama<0.5.0,>=0.3.9
#5 2.244   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
#5 2.263 Collecting tzlocal<3.0,>=1.4
#5 2.270   Downloading tzlocal-2.1-py2.py3-none-any.whl (16 kB)
#5 2.509 Collecting aiohttp<3.8.0,>=3.5.4
#5 2.524   Downloading aiohttp-3.7.4.post0-cp38-cp38-manylinux2014_aarch64.whl (1.5 MB)
#5 2.592 Collecting asahi<0.2.0,>=0.1.0
#5 2.600   Downloading asahi-0.1.1-py3-none-any.whl (3.6 kB)
#5 2.617 Collecting pamqp<3,>=2.2.0
#5 2.627   Downloading pamqp-2.3.0-py2.py3-none-any.whl (28 kB)
#5 2.675 Collecting botocore>=1.12.252
#5 2.684   Downloading botocore-1.20.106-py2.py3-none-any.whl (7.7 MB)
#5 2.962 Collecting wrapt>=1.10.10
#5 2.975   Downloading wrapt-1.13.3.tar.gz (48 kB)
#5 3.107 Collecting aioitertools>=0.5.1
#5 3.116   Downloading aioitertools-0.8.0-py3-none-any.whl (21 kB)
#5 3.135 Collecting chardet<5.0,>=2.0
#5 3.142   Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
#5 3.384 Collecting multidict<7.0,>=4.5
#5 3.400   Downloading multidict-5.2.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (138 kB)
#5 3.421 Collecting attrs>=17.3.0
#5 3.427   Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
#5 3.544 Collecting yarl<2.0,>=1.0
#5 3.553   Downloading yarl-1.7.2-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (317 kB)
#5 3.574 Collecting typing-extensions>=3.6.5
#5 3.581   Downloading typing_extensions-4.0.0-py3-none-any.whl (22 kB)
#5 3.596 Collecting async-timeout<4.0,>=3.0
#5 3.603   Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
#5 3.639 Collecting python-dateutil<3.0.0,>=2.1
#5 3.645   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
#5 3.684 Collecting urllib3<1.27,>=1.25.4
#5 3.690   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
#5 3.710 Collecting jmespath<1.0.0,>=0.7.1
#5 3.718   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
#5 3.747 Collecting six>=1.5
#5 3.756   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
#5 3.790 Collecting idna>=2.0
#5 3.796   Downloading idna-3.3-py3-none-any.whl (61 kB)
#5 3.808 Building wheels for collected packages: aiobotocore, cchardet, wrapt
#5 3.808   Building wheel for aiobotocore (setup.py): started
#5 3.951   Building wheel for aiobotocore (setup.py): finished with status 'done'
#5 3.952   Created wheel for aiobotocore: filename=aiobotocore-1.3.3-py3-none-any.whl size=48358 sha256=cb41746b01ee64cc5bb977fd1c5631273e83aa057c95fe2966435328712061c4
#5 3.952   Stored in directory: /root/.cache/pip/wheels/89/77/d7/6381c7bd3834688c6d98fbfe742779bf2b336f304035adca0d
#5 3.954   Building wheel for cchardet (setup.py): started
#5 4.051   Building wheel for cchardet (setup.py): finished with status 'error'
#5 4.051   ERROR: Command errored out with exit status 1:
#5 4.051    command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ii80ekq0/cchardet_e5f214b4360248e6b57958991b42d42d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ii80ekq0/cchardet_e5f214b4360248e6b57958991b42d42d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-uov3lue1
#5 4.051        cwd: /tmp/pip-install-ii80ekq0/cchardet_e5f214b4360248e6b57958991b42d42d/
#5 4.051   Complete output (20 lines):
#5 4.051   running bdist_wheel
#5 4.051   running build
#5 4.051   running build_py
#5 4.051   creating build
#5 4.051   creating build/lib.linux-aarch64-3.8
#5 4.051   creating build/lib.linux-aarch64-3.8/cchardet
#5 4.051   copying src/cchardet/version.py -> build/lib.linux-aarch64-3.8/cchardet
#5 4.051   copying src/cchardet/__init__.py -> build/lib.linux-aarch64-3.8/cchardet
#5 4.051   running build_ext
#5 4.051   building 'cchardet._cchardet' extension
#5 4.051   creating build/temp.linux-aarch64-3.8
#5 4.051   creating build/temp.linux-aarch64-3.8/src
#5 4.051   creating build/temp.linux-aarch64-3.8/src/cchardet
#5 4.051   creating build/temp.linux-aarch64-3.8/src/ext
#5 4.051   creating build/temp.linux-aarch64-3.8/src/ext/uchardet
#5 4.051   creating build/temp.linux-aarch64-3.8/src/ext/uchardet/src
#5 4.051   creating build/temp.linux-aarch64-3.8/src/ext/uchardet/src/LangModels
#5 4.051   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/ext/uchardet/src -I/usr/local/include/python3.8 -c src/cchardet/_cchardet.cpp -o build/temp.linux-aarch64-3.8/src/cchardet/_cchardet.o
#5 4.051   unable to execute 'gcc': No such file or directory
#5 4.051   error: command 'gcc' failed with exit status 1
#5 4.051   ----------------------------------------
#5 4.051   ERROR: Failed building wheel for cchardet
#5 4.052   Running setup.py clean for cchardet
#5 4.136   Building wheel for wrapt (setup.py): started
#5 4.263   Building wheel for wrapt (setup.py): finished with status 'done'
#5 4.263   Created wheel for wrapt: filename=wrapt-1.13.3-cp38-cp38-linux_aarch64.whl size=20269 sha256=eb5b85afe5eeebdff11d600e4f81431ee8af6f19c4a25864dbf681d96ba5f0cb
#5 4.264   Stored in directory: /root/.cache/pip/wheels/bb/05/57/f0c531fdf04b11be18b21ab4d1ec5586a6897caa6710c2a1a5
#5 4.265 Successfully built aiobotocore wrapt
#5 4.265 Failed to build cchardet
#5 4.346 Installing collected packages: six, multidict, idna, yarl, urllib3, typing-extensions, python-dateutil, jmespath, chardet, attrs, async-timeout, wrapt, pytz, pamqp, botocore, aioitertools, aiohttp, tzlocal, colorama, cchardet, asahi, aiobotocore, aioamqp, tomodachi
#5 5.092     Running setup.py install for cchardet: started
#5 5.190     Running setup.py install for cchardet: finished with status 'error'
#5 5.190     ERROR: Command errored out with exit status 1:
#5 5.190      command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ii80ekq0/cchardet_e5f214b4360248e6b57958991b42d42d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ii80ekq0/cchardet_e5f214b4360248e6b57958991b42d42d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tq7rc9z8/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/cchardet

**Comment by kalaspuff** [comment]
Example cases fixed by using another base-image.
