### ISSUE TITLE
File caches

### ISSUE THREAD

**Issue by smaaland** [kalaspuff/tomodachi#36]
It seems like the python file caches are not being correctly reloaded by the watcher. 

If I change a variable in a method that has a http decorator while the service is being run with the watcher on, the variable change does not get any effect when I perform a new request (after the watcher has reloaded everything). However if I stop the service and start it again, it works. 

The same thing happens both when I run it in a Docker container, and when I run it straight through the cli.

**Comment by smaaland** [comment]
Some more information from digging around with this.. It does not happen in an __init__(self) function inside a service, if I do the exact same thing inside that function (assigning a variable and just printing it). So the init function does not seem to be cached like the actual service calls..

But it also do happen if I create new functions, and calls them from inside the service functions though, so it seems to be an issue with just normal functions as well (both static and non-static).

**Comment by kalaspuff** [comment]
Fixed in 0.2.5 release!
