### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by smaaland** [kalaspuff/tomodachi#37]
With the current requirements.txt the service is not able to start:

pkg_resources.DistributionNotFound: The 'botocore<=1.5.38,>=1.5.0' distribution was not found and is required by aiobotocore

The version number for botocore in the requirements (botocore==1.5.48) is too new for aiobotocore.

**Comment by kalaspuff** [comment]
Fixed in release 0.2.4! Added test to catch these issues earlier.
