### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by japrogramer** [kalaspuff/tomodachi#661]
https://github.com/kalaspuff/tomodachi/blob/50f5eebc4aeadc4a007415db440db9c056a8ad82/examples/basic_examples/http_auth_service.py#L13

wouldn't this line cause 
AttributeError: 'NoneType' object has no attribute 'decode'
if the line before it returns None?

**Comment by kalaspuff** [comment]
You're completely correct. 🤦‍♂️
