### ISSUE TITLE
Missing Example: No Example for websockets

### ISSUE THREAD

**Issue by japrogramer** [kalaspuff/tomodachi#662]
An example for the basic websocket use cases is not available.

**Comment by kalaspuff** [comment]
There's some code available in the https://github.com/kalaspuff/tomodachi/blob/master/examples/basic_examples/http_simple_service.py that listens for WS connections.

I also added the https://github.com/kalaspuff/tomodachi/tree/master/examples/basic_examples/websockets example which basically does the same. The `index` file here could probably fail with the current released version of `tomodachi`, as there's a fix in master branch that's still not released. WS connection however should still work if the `index.html` is opened independently from the service.
