### ISSUE TITLE
RecursionError (Python 3.6)

### ISSUE THREAD

**Issue by smaaland** [kalaspuff/tomodachi#72]
When adding the line `from typing import Dict` at the top of the example http_service (for example), the service starts as usual, and works. However, the first time the watcher reloads the service, the entire service crashes, and somehow ends up in a `RecursionError: maximum recursion depth exceeded while calling a Python object`.

**Comment by kalaspuff** [comment]
Problem doesn't occur in Python 3.5.x or Python 3.6.0, but started happening in Python 3.6.1. I've added a list of safe modules that may never be removed from the list of already loaded modules when the watcher triggers. Including `typing` in this list seems to avoid the RecursionError problem.

New release which includes the fix – 0.2.9. https://github.com/kalaspuff/tomodachi/releases/tag/0.2.9
