### ISSUE TITLE
Queuing and Exchange Operations

### ISSUE THREAD

**Issue by folt** [kalaspuff/tomodachi#918]
Your library is just a find for me. But I did not find an example for creating a stock exchange and a queue. Is it possible to perform such operations through this library for a rabbitmq?

**Comment by kalaspuff** [comment]
This is a really old question, which haven't been addressed. Sorry for that. 😓 Today there should be additional documentation available for presenting possible solutions to using topic-exchanges on RabbitMQ, and possibly how to extend such a functionality for using this with custom exchanges.
